site_name: Twillow Docs

theme:
  name: material
  # custom_dir: docs/overrides

  palette:
    scheme: slate
    primary: light blue

  features:
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.share

nav:
  - Homepage:
    - index.md

  - Tutorials:
    - Setting up Google CSE: tutorials/google-cse.md

  - Module Development:
    - Module Development with Lua (Recommended): module-dev/lua.md
    - Module Development with Python: module-dev/python.md

markdown_extensions:
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true

