account_sid = 'YourTwilioAccountSID'
auth_token = 'YourTwilioAuthToken'

from_number = '+15555555555' # Number to send messages from
to_number = '+15555555555' # Number to send messages to by default

voice_handler = '' # Specify a location for a voice handler

modules = [
    # Miscellaneous Modules
    './modules/misc/ping.lua',
    './modules/misc/8ball.lua',
    './modules/misc/media.lua',
    './modules/misc/search.py',
    # Custom Modules
]

[module.search]
# See docs/google-cse.md
google_api_key = 'YourAPIKey'
google_cse_id = 'YourSearchEngineID'
